version: 2.1
orbs:
  docker: circleci/docker@1.0.1

jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: figedi/circleci-node-gcloud
          tag: $CIRCLE_SHA1,latest
      - docker/push:
          digest-path: /tmp/digest.txt
          image: figedi/circleci-node-gcloud
          tag: $CIRCLE_SHA1,latest
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  commit:
    jobs:
      - build-and-push